[pytest]
testpaths = tests
addopts = --cov=. --cov-report=xml --cov-report=term-missing

[coverage:run]
omit = tests/*,tools/*,montador.py

[coverage:report]
exclude_lines =
    pragma: no cover
    if __name__ == .__main__.
