sonar.projectKey=joaovitorgalvao80-rgb_teste
sonar.organization=joaovitorgalvao80-rgb
sonar.sources=.
sonar.exclusions=tests/**,tools/**,.smoke_runtime/**,static/**,templates/**,services/source_discovery.py
sonar.test.exclusions=tests/**
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11
